import LegalPage, { LegalSection } from '../components/LegalPage'

export default function Privacy() {
  return (
    <LegalPage title="Privacy Policy">
      <p>This policy describes how NOMI, an AI-assisted productivity service for Gmail and Google Calendar, handles information when you use the service.</p>
      <LegalSection title="Google Workspace data"><p>When you connect a Google account and authorize the requested permissions, NOMI may access Google Workspace information needed for the feature you request. Gmail information can include sender and recipient details, email subjects, dates, message and thread IDs, labels, snippets, and message content when the requested operation requires it. Calendar information can include event titles and details, dates and times, attendees, locations, and conferencing information. The information accessed depends on your request and the permissions granted through Google OAuth.</p><p className="mt-2">NOMI uses this information to provide requested features, including searching or retrieving Gmail information, drafting, replying to or sending email, marking messages as read, creating or managing Calendar events, and generating Google Meet links where applicable. Google Workspace data is not used for advertising.</p><p className="mt-2">NOMI's use and transfer of information received from Google Workspace APIs complies with the Google API Services User Data Policy, including the Limited Use requirements.</p></LegalSection>
      <LegalSection title="AI processing and Google data"><p>When AI processing is needed, NOMI sends relevant information to Groq for inference. NOMI currently accesses <code>openai/gpt-oss-20b</code> through Groq as its primary model and <code>openai/gpt-oss-120b</code> through Groq as its fallback model. Despite the model names, NOMI does not directly send data to OpenAI or use the OpenAI API for these models.</p><p className="mt-2">Information in an AI request may include content derived from Google Workspace and conversation or context information needed to carry out your request. NOMI applies pattern-based privacy processing that attempts to detect and redact certain sensitive values before model processing. This does not guarantee detection or removal of every sensitive identifier or personal detail.</p><p className="mt-2">NOMI's Groq organization has Inference APIs Zero Data Retention (ZDR) enabled. Groq receives and processes information to provide inference. With Inference APIs ZDR enabled, NOMI's inference inputs and outputs are not retained for Groq's system reliability or abuse-monitoring logging. This statement concerns inference API processing only.</p><p className="mt-2">NOMI does not authorize the use of Google Workspace API data received through NOMI to train or fine-tune general AI models. NOMI does not itself train models using Google Workspace data.</p><p className="mt-2">Sending an email requires separate, explicit approval. You can review and edit the proposed recipient, subject, and body before approving it; email sending has no persistent “always allow” setting.</p></LegalSection>
      <LegalSection title="Information stored and retention"><p>NOMI stores application data in MongoDB, including internal user identifiers linked to Firebase Authentication; email, display name, profile photo, country and time zone; connected Google account identifiers, profile information, granted scopes and encrypted access and refresh tokens; chat titles, summaries and messages; permission choices; action and audit records; and temporary conversation, OAuth, workflow, and pending email approval state. Chats can contain information you type and responses or relevant email and Calendar details. Chat records have no configured automatic expiry, but you can delete individual chats in the app.</p><p className="mt-2">Temporary conversation context can contain relevant retrieved snippets, event details, identifiers, and pending workflow state. Its expiry is renewed during use and is set to one year after the most recent update; database cleanup may happen later. Pending email approvals expire after 10 minutes. OAuth state is short-lived. Uploaded attachments are stored with Cloudinary when attachment storage is configured; NOMI stores file metadata in MongoDB and schedules attachment cleanup after two hours, subject to cleanup processing.</p><p className="mt-2">NOMI does not provide an account-wide in-app deletion control or publish a privacy-request contact channel. Disconnecting Google removes stored connection credentials and attempts to revoke the token, but does not delete chat or account data and cannot remove information Google retains.</p></LegalSection>
      <LegalSection title="Service providers"><p>NOMI uses Google APIs for Gmail, Calendar, and Google sign-in; Firebase Authentication for NOMI account authentication; MongoDB for application records; Groq for AI processing; Cloudinary for uploaded attachment storage when configured; Vercel to host the frontend; and Render to run the backend. Each provider processes information as needed for its respective service; not every provider receives Google Workspace data. Providers are subject to their own terms and privacy practices.</p></LegalSection>
      <LegalSection title="Security and controls"><p>NOMI uses Firebase authentication, server-side user and authorization checks, encrypted storage for Google tokens, and approval controls for actions such as sending email. Users may configure persistent permissions for some other actions and remove them in Settings. NOMI aims to limit sensitive information in logs. No online service can be guaranteed completely secure.</p><p className="mt-2">You can disconnect Google in NOMI Settings or revoke NOMI's access in your Google Account security settings. You can remove individual chats in the app. Disconnecting or revoking access may stop connected features from working. There is currently no account-wide self-service deletion control.</p></LegalSection>
      <LegalSection title="Children"><p>NOMI is a general productivity service and is not designed for children.</p></LegalSection>
      <LegalSection title="Contact"><p>The project does not currently publish a privacy email address or support channel in the application or project configuration. No contact address is provided here because NOMI has not published one.</p></LegalSection>
    </LegalPage>
  )
}
