import LegalPage, { LegalSection } from '../components/LegalPage'

export default function Privacy() {
  return (
    <LegalPage title="Privacy Policy">
      <p>Effective date: September 30, 2026. This policy describes how NOMI, an AI-powered productivity assistant for Gmail and Google Calendar, handles information when you use the service.</p>
      <LegalSection title="Google data NOMI accesses"><p>After you connect a Google account and grant OAuth permissions, NOMI may access Gmail messages and metadata needed for the features you request, including sender and recipient addresses, subject, message and thread identifiers, dates, labels, snippets, and message content. It may access Calendar events and related details such as titles, descriptions, times, attendees, locations, and conference information needed to find, create, update, or delete events. Google sign-in and the connected integration also provide account identifiers, email address, profile name or photo, and granted-scope information. The requested scopes cover basic OpenID/profile/email information, Gmail read/modify/compose/send, and Calendar access. Actual operations depend on the feature used and permissions Google grants.</p><p className="mt-2">NOMI uses this information to carry out your requests: searching or reading relevant email, drafting or replying, preparing attachments, marking messages as read, finding or managing calendar events, and creating Google Meet links. Google data is not used for advertising or unrelated purposes.</p></LegalSection>
      <LegalSection title="Data minimization and processing"><p>NOMI is designed to retrieve relevant Gmail or Calendar information when needed rather than intentionally keeping a permanent copy of your entire inbox or calendar history. Some relevant results and message content may be kept in chat records or temporary server-side context as described below. NOMI prepares AI inputs through a privacy layer that redacts detected personal identifiers where applicable, but this does not guarantee that every sensitive detail is removed.</p><p className="mt-2">NOMI uses AI to understand requests and help generate responses and proposed actions. Its implemented AI integration sends the request and relevant retrieved content to Groq when Groq is configured. NOMI does not make a claim here about Groq's retention or use of submitted data. Sending an email requires a separate, explicit approval. You can review and edit the proposed recipient, subject, and body before approval. There is no permanent “always allow” setting for email sending.</p></LegalSection>
      <LegalSection title="Information stored and retention"><p>NOMI stores application data in MongoDB, including internal user identifiers linked to Firebase Authentication; email, display name, profile photo, country and time zone; connected Google account identifiers, profile information, granted scopes and encrypted access/refresh tokens; chat titles, summaries and messages; permission choices; action/audit records; and temporary conversation, OAuth and pending-action state. Chat messages and summaries can contain information you type and responses or relevant email/calendar details. Chat records have no configured automatic expiry, but you can delete individual chats in the app.</p><p className="mt-2">Temporary conversation context can contain relevant retrieved snippets, event details, identifiers and pending workflow state. Its expiry is renewed during use and is set to one year after the most recent update; database cleanup may happen later. Pending email-send approvals expire after 10 minutes. OAuth state is short-lived. Uploaded attachments are stored with Cloudinary when attachment storage is configured; NOMI stores file metadata in MongoDB and schedules attachment cleanup after two hours, subject to cleanup processing. NOMI does not provide an account-wide in-app deletion control or publish a privacy-request contact channel, so there is no in-product way to request account-wide deletion. Disconnecting Google removes the stored connection credentials and attempts to revoke the token, but does not delete chat or account data and cannot remove information Google retains.</p></LegalSection>
      <LegalSection title="Service providers"><p>NOMI uses Google APIs for Gmail, Calendar and Google sign-in; Firebase Authentication for NOMI account authentication; MongoDB for application records; Groq for AI processing when configured; Cloudinary for uploaded attachment storage when configured; Vercel to host the frontend; and Render to run the backend. These providers process information as needed to provide their respective services and are subject to their own terms and privacy practices.</p></LegalSection>
      <LegalSection title="Security and controls"><p>NOMI uses Firebase authentication, server-side user and authorization checks, encrypted storage for Google tokens, and temporary server-side pending actions. Email sending requires per-action approval; users may configure persistent permissions for some other actions and can remove them in Settings. NOMI aims to limit sensitive information in logs. No online service can be guaranteed completely secure.</p><p className="mt-2">You can disconnect Google in NOMI Settings or revoke NOMI's access in your Google Account security settings. You can remove individual chats in the app. Disconnecting or revoking access may stop connected features from working. There is currently no account-wide self-service deletion control.</p></LegalSection>
      <LegalSection title="Children"><p>NOMI is a general productivity service and is not designed for children.</p></LegalSection>
      <LegalSection title="Contact"><p>The project does not currently publish a privacy email address or support channel in the application or project configuration. No contact address is provided here because NOMI has not published one.</p></LegalSection>
    </LegalPage>
  )
}
