import LegalPage, { LegalSection } from '../components/LegalPage'

export default function Privacy() {
  return (
    <LegalPage title="Privacy Policy">
      <p>This Privacy Policy explains how NOMI handles information when you use NOMI, an AI-assisted productivity service for working with email and calendars.</p>
      <LegalSection title="Google account information"><p>NOMI can access Google Gmail and Google Calendar data only after you connect a Google account and grant the requested Google permissions. Depending on the permissions granted and the task you request, this may include email messages and metadata (such as senders, recipients, subjects, dates, thread or message identifiers, and message content needed to search, summarize, draft, or reply), and calendar events and related calendar information (such as event titles, times, attendees, descriptions, and availability) needed to find, create, update, or otherwise handle an event.</p><p className="mt-2">NOMI uses Google data only to provide the features you request. Google user data is not used for advertising or unrelated purposes, and NOMI does not sell personal information.</p></LegalSection>
      <LegalSection title="Retrieval and processing"><p>Relevant information may be retrieved from Google when needed to fulfill a request and processed by NOMI's services and, where needed to generate a response, its AI service provider. Processing can include the request and relevant retrieved content. NOMI applies data-minimization and privacy-boundary measures, including reducing personal details in AI inputs where applicable.</p><p className="mt-2">NOMI does not intentionally maintain a permanent copy of your entire Gmail inbox or calendar history in its database. This is different from saying no Google-related data is stored: limited, relevant information may be held temporarily in conversation context to complete follow-up requests.</p></LegalSection>
      <LegalSection title="Temporary and persistent data"><p>Temporary conversation context can include your messages, relevant retrieved snippets or event details, provider identifiers needed to continue an action, and related temporary state. Conversation context is configured to expire after approximately one year of inactivity; cleanup timing depends on database TTL processing. Pending send approvals and OAuth state also have expiration behavior. Uploaded attachment references are short-lived.</p><p className="mt-2">NOMI also stores persistent application data in MongoDB, including internal account identifiers linked to Firebase Authentication, account profile details you provide, connected Google account identifiers and granted scopes, encrypted Google access/refresh tokens, chat session titles and summaries, chat messages, permission/action decisions, pending action state, and security or action audit metadata. Chat sessions and messages do not have a configured automatic retention period in the application. Deleting a chat from the app removes its messages. Disconnecting Google removes NOMI's stored Google credentials and connection record through the available connected-account controls; this does not itself erase other application records or change data retained by Google.</p></LegalSection>
      <LegalSection title="Actions and your choices"><p>Sensitive actions, including sending an email, require your explicit approval in NOMI. Some other actions can be permitted once or marked as always allowed in your settings. Review proposed content and changes before approving them.</p><p className="mt-2">You can disconnect Google through NOMI's Settings where available and revoke NOMI's access in your Google Account security settings. Revoking access can prevent connected features from working. You can also delete individual chats from the app. NOMI currently does not provide an in-app account-wide deletion control; Firebase account records and other retained application data may require a separate deletion process.</p></LegalSection>
      <LegalSection title="Security"><p>NOMI uses measures intended to protect information, including server-side access controls and encryption of stored Google tokens. No online service or transmission method can be guaranteed completely secure.</p></LegalSection>
      <LegalSection title="Contact"><p>The project currently does not publish a dedicated privacy contact address or support channel in the application. This policy will be updated if NOMI's data practices change.</p></LegalSection>
    </LegalPage>
  )
}
