import LegalPage, { LegalSection } from '../components/LegalPage'

export default function Terms() {
  return (
    <LegalPage title="Terms of Service">
      <p>These Terms govern your use of NOMI. By accepting them and using the service, you agree to them. If you do not agree, do not use NOMI.</p>
      <LegalSection title="Service and accounts"><p>NOMI is an AI-assisted productivity service that helps you work with Gmail and Google Calendar through natural-language requests. You are responsible for your account and for keeping your sign-in credentials secure. You must have the rights and authority to connect each Google account, grant requested permissions, and access or act on its information. Google's own terms and policies also apply to your use of Google services.</p></LegalSection>
      <LegalSection title="Your review and responsibility"><p>AI-generated responses can be inaccurate, incomplete, outdated, or inappropriate. You are responsible for reviewing them before relying on them or taking action. Check email recipients, subject and body, attachments, calendar details, dates, times, attendees, and other proposed changes. NOMI can perform actions that affect external services when you authorize them. You remain responsible for reviewing those actions and ensuring you have authority to perform them. Sending an email requires your explicit approval in NOMI; you can review and edit the proposed email before approving it.</p></LegalSection>
      <LegalSection title="Uploaded contacts and personalized email"><p>You are responsible for information you upload to NOMI, including names, email addresses, spreadsheets, and other recipient lists. You must have appropriate rights or authorization to use recipient information with NOMI. When contacting recipients, you must have a lawful basis or appropriate permission where required, use accurate recipient information, review generated messages before sending where applicable, and comply with applicable anti-spam, privacy, marketing, and communications laws.</p></LegalSection>
      <LegalSection title="Acceptable use"><p>You may not use NOMI for spam, phishing, fraudulent communications, harassment, deceptive mass messaging, malicious campaigns, or unlawful communications. You may not use NOMI to break the law, infringe another person's rights, send unlawful or abusive communications, access or process information without authorization, evade Google permissions or policies, interfere with the service, probe or bypass its security, or disrupt other users' access. Do not use NOMI to transmit malicious code or misrepresent your identity.</p></LegalSection>
      <LegalSection title="Third-party services and availability"><p>NOMI depends on third-party services, including Google, Firebase, AI providers, and hosting and storage providers. Their services are governed by their own terms and may change or become unavailable. Google integrations may also change, be limited, or become unavailable under Google's terms and policies. NOMI is an early-stage service; features may change, and access or individual actions may be interrupted, delayed, or unavailable. Uninterrupted availability or successful completion of every request is not promised.</p></LegalSection>
      <LegalSection title="Intellectual property and your content"><p>The NOMI application, branding, and original materials are owned by the project or its licensors. These Terms grant you a limited, revocable, non-transferable right to use NOMI for its intended purpose. You retain rights you hold in content you submit. You allow NOMI to process that content as needed to operate the service and carry out your requests. Third-party services and materials remain subject to their owners' rights and terms.</p></LegalSection>
      <LegalSection title="Disclaimers and liability"><p>To the extent permitted by applicable law, NOMI is provided “as is” and “as available.” The project does not warrant that the service will be uninterrupted, error-free, or that AI output will be accurate. These Terms do not exclude warranties or rights that applicable law does not allow to be excluded.</p><p className="mt-2">To the extent permitted by applicable law, the project is not liable for indirect, incidental, special, consequential, or punitive losses arising from use of NOMI. Nothing here limits liability or rights that cannot lawfully be limited or waived. This section is not legal advice.</p></LegalSection>
      <LegalSection title="Suspension and termination"><p>You may stop using NOMI and disconnect Google at any time through Settings or your Google Account. We may suspend or end access when reasonably necessary for misuse, security, legal or operational reasons. Ending access does not automatically delete your account or application data. See the Privacy Policy for available controls and retention details.</p></LegalSection>
      <LegalSection title="Changes and contact"><p>These Terms may be updated as NOMI changes. The updated version will be posted here with a revised effective date. Continued use after an update constitutes acceptance to the extent permitted by law. The project does not currently publish a dedicated legal or support contact address in the application or project configuration.</p></LegalSection>
    </LegalPage>
  )
}
