import LegalPage, { LegalSection } from '../components/LegalPage'

export default function Terms() {
  return (
    <LegalPage title="Terms of Service">
      <p>These Terms of Service govern your access to and use of NOMI. By creating an account or using NOMI, you agree to these Terms. If you do not agree, do not use the service.</p>
      <LegalSection title="Using NOMI"><p>NOMI is an AI-assisted productivity tool that helps you work with email and calendar services through conversational requests. You must provide accurate account information, keep your sign-in credentials secure, and use NOMI only as permitted by law and these Terms.</p><p className="mt-2">You must have the rights and authority to connect each Google account and authorize NOMI to access the information and perform the actions you request. You are responsible for complying with Google's terms and policies when using your Google account.</p></LegalSection>
      <LegalSection title="Review and approval"><p>AI-generated results may be incomplete, misleading, or inaccurate. You are responsible for reviewing generated emails, calendar actions, and other outputs before relying on them. Review recipients, content, dates, times, and other details carefully. Sensitive actions such as sending an email require your approval in NOMI; your approval makes you responsible for authorizing that action.</p></LegalSection>
      <LegalSection title="Acceptable use"><p>You may not use NOMI to violate law or another person's rights, send abusive or unlawful communications, interfere with the service or its security, attempt unauthorized access, or use the service in a way that violates Google policies or the permissions you granted. You may not misrepresent your identity or use NOMI to process information you are not authorized to access.</p></LegalSection>
      <LegalSection title="Availability and changes"><p>NOMI is an early-stage service provided with reasonable operational efforts. Features may change, be interrupted, or become unavailable, including when third-party services, network access, or granted permissions are unavailable. We do not promise uninterrupted availability or that every requested action will succeed.</p></LegalSection>
      <LegalSection title="Intellectual property"><p>NOMI and its software, branding, and original materials are owned by the project or its licensors. These Terms give you a limited, personal, revocable right to use the service. You retain rights to content you provide; you allow NOMI to process that content as needed to operate and provide the features you request. Third-party services and materials remain subject to their owners' terms.</p></LegalSection>
      <LegalSection title="Disclaimer and liability"><p>To the extent permitted by applicable law, NOMI is provided “as is” and “as available,” without warranties that cannot lawfully be excluded. NOMI does not warrant that generated results will be accurate or that the service will always be available or error-free.</p><p className="mt-2">To the extent permitted by applicable law, the project will not be liable for indirect, incidental, special, consequential, or punitive losses arising from use of the service. Nothing in these Terms excludes or limits liability where applicable law does not allow it, or affects rights that cannot be waived.</p></LegalSection>
      <LegalSection title="Suspension and termination"><p>You may stop using NOMI and disconnect Google at any time. We may suspend or end access where reasonably necessary to address misuse, security concerns, legal requirements, or operational changes. Ending access does not automatically delete application data; see the Privacy Policy for current controls and retention details.</p></LegalSection>
      <LegalSection title="Changes and contact"><p>We may update these Terms as the service evolves. Updated Terms will be posted here with a revised effective date. The project currently does not publish a dedicated support or legal contact channel in the application.</p></LegalSection>
    </LegalPage>
  )
}
